include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:

linter:
  rules:
    prefer_relative_imports: true
    always_use_package_imports: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false
    sort_pub_dependencies: false
