name: cupertino_icons_gallery
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  # state management
  flutter_riverpod: ^2.4.9

  # search highlight
  substring_highlight: ^1.0.33

  # navigation and routing
  go_router: ^12.1.3

  # fonts
  google_fonts: ^6.1.0

  # scrollable rows x columns
  flextras: ^1.0.0

  # scrollbars
  draggable_scrollbar: ^0.1.0

  # Animating Text
  animated_text_kit: ^4.2.2

  # opening urls
  url_launcher: ^6.2.2

  # icons
  ionicons: ^0.2.2

  # svgs
  flutter_svg: ^2.0.9

  # firebase
  firebase_core: ^2.24.2

  # splash screen
  flutter_native_splash: ^2.3.8

  firebase_analytics: ^10.7.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_launcher_icons: ^0.13.1
  import_sorter: ^4.6.0
  very_good_analysis: ^5.1.0
  
flutter:
  uses-material-design: true

  assets:
    - images/
